### PR TITLE
Fix: base path and use xdg crate

### PR DESCRIPTION
**Pull request by oknozor**
Hey @wash2 do you plan to fix more stuff here or can I merge as is ?

### CODE REVIEW

**Comment by wash2** [comment]
Oh thanks! Ya I was meaning to put together a PR. This should be good as is as far as I can tell :)

**Comment by wash2** [comment]
I think sometimes it seems like a strange size is picked for certain icons, specifically for firefox in my case. Maybe searching for svg first by default would avoid it in most cases but I can look more into the issue in general. It might just be that I'm using it incorrectly lol

**Comment by oknozor** [comment]
Maybe related to #4, I need to take a closer look though

**Comment by oknozor** [comment]
Hey @wash2 I have just released the crate with your changes. 
It's now available on crates.io

**Pull request merged**
