### PR TITLE
fix: Use directories without index if defined elsewhere

### LINKED ISSUE #11: Incorrectly skips theme directories containing no index.theme file
The specification says:

> In *at least one* of the theme directories there must be a file called index.theme that describes the theme. The first index.theme found while searching the base directories in order is used. This file describes the general attributes of the theme. 

However this library implements theme searching more like "In *all* of the theme directories".

For example `~/.local/share/icons/hicolor` is skipped if it lacks a `index.theme` file even though `/usr/share/icons/hicolor/index.theme` exist.

### PR DESCRIPTION
**Pull request by Pajn**
Fixes #11 

This was the smallest change I could come up with in the current structure. A more semantically correct implementation would probably be to add support for multiple paths in the theme struct but that caused a lot more changes for what I think is only an academic difference.

### CODE REVIEW

**Comment by LucaCoduriV** [comment]
@oknozor  Could you please approve this pr ? It can fix an issue I have.

**Comment by LucaCoduriV** [comment]
Never mind, I have icons in ~/.local/share/icons but even with this fix it still doesn't work :(

**Comment by wash2** [comment]
> Never mind, I have icons in ~/.local/share/icons but even with this fix it still doesn't work :(

Did you check that `~/.local/share` is in XDG_DATA_DIRS?

**Comment by oknozor** [comment]
Hey, thanks to this is solved @wash2, also it's no longer needed to set XDG_DATA_DIRS manually.

**Pull request closed without merging**
